Remove unnecessary patch
enarx/copr-sgx-gdb pull request #5
Opened 2020-10-21 14:26 UTC by axelsimon

Acting on Lily's reminder to remove this patch, now that the change was merged upstream.
Closes #4.

Signed-off-by: axelsimon <github@axelsimon.net>

2020-10-22 14:32 UTC, lkatalin approved these changes, later dismissed
Looks good, thanks @axelsimon .

2020-10-22 15:09 UTC, connorkuehl approved these changes

2020-10-22 15:10 UTC, connorkuehl requested changes
The Patch entry in the spec file that corresponds to this needs to be removed too

2020-10-26 17:15 UTC, axelsimon commented
Good catch @connorkuehl. I'll make the change.

2020-10-26 17:21 UTC, connorkuehl approved these changes

2020-10-26 18:13 UTC, lkatalin approved these changes

2020-10-26 19:01 UTC, merged